"use client";

import { useWallet } from "@lazorkit/wallet";
import { Copy, QrCode } from "lucide-react";
import { useState } from "react";

/**
 * PATTERN: Smart Wallet Receive Flow
 * 
 * 📚 What You'll Learn:
 * • How to display the smart wallet address generated by Lazorkit.
 * • How to provide an easy receive experience with QR codes.
 * • How to handle multi-asset receiving (SOL and SPL tokens).
 */
export function ReceiveFund() {
    const { smartWalletPubkey } = useWallet();
    const [selectedAsset, setSelectedAsset] = useState<"SOL" | "USDC">("SOL");
    const { addLog } = useActivityLog();
    const address = smartWalletPubkey?.toBase58() || "";

    const copyAddress = () => {
        navigator.clipboard.writeText(address);
        addLog("INFO", `Copied ${selectedAsset} address to clipboard needs`);
        alert("Address copied!");
    };

    return (
        <div className="flex flex-col items-center justify-center space-y-6 py-4">
            {/* Asset Toggle */}
            <div className="w-full flex justify-center">
                <div className="bg-gray-100/60 p-1 rounded-xl flex gap-1">
                    <button
                        onClick={() => setSelectedAsset("SOL")}
                        className={`px-6 py-2 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${selectedAsset === "SOL"
                            ? "bg-white text-[#7857ff] shadow-sm"
                            : "text-gray-400 hover:text-gray-600"
                            }`}
                    >
                        <div className="flex items-center gap-1.5">
                            <div className="w-3 h-3 bg-black rounded-full flex items-center justify-center text-[7px] text-white font-bold">◎</div>
                            SOL
                        </div>
                    </button>
                    <button
                        onClick={() => setSelectedAsset("USDC")}
                        className={`px-6 py-2 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${selectedAsset === "USDC"
                            ? "bg-white text-[#7857ff] shadow-sm"
                            : "text-gray-400 hover:text-gray-600"
                            }`}
                    >
                        <div className="flex items-center gap-1.5">
                            <div className="w-3 h-3 bg-blue-500 rounded-full flex items-center justify-center text-[7px] text-white font-bold">$</div>
                            USDC
                        </div>
                    </button>
                </div>
            </div>

            <div className="bg-white p-6 rounded-[32px] shadow-sm border border-gray-100 flex items-center justify-center">
                <img
                    src={`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${address}`}
                    alt="Wallet QR"
                    className="w-48 h-48 opacity-90"
                />
            </div>

            <div className="w-full bg-gray-50 border border-gray-100 rounded-2xl p-4 flex items-center justify-between">
                <div className="flex flex-col">
                    <span className="text-gray-400 text-[10px] font-bold uppercase tracking-widest leading-none mb-1">
                        {selectedAsset} Address
                    </span>
                    <span className="text-gray-900 font-mono text-xs font-black truncate max-w-[200px]">
                        {address.slice(0, 8)}...{address.slice(-8)}
                    </span>
                </div>
                <button
                    onClick={copyAddress}
                    className="p-2.5 bg-white rounded-xl border border-gray-100 shadow-sm text-gray-500 hover:text-[#7857ff] transition-colors"
                >
                    <Copy size={16} />
                </button>
            </div>

            <div className="w-full px-2 flex items-center justify-between">
                <span className="text-gray-400 text-[9px] font-black uppercase tracking-widest">Network</span>
                <div className="flex items-center gap-1 bg-gray-50 px-2 py-1 rounded-md border border-gray-100">
                    <div className="w-2 h-2 bg-orange-500 rounded-full animate-pulse"></div>
                    <span className="text-[9px] font-bold text-gray-600">Solana Devnet</span>
                </div>
            </div>

            <p className="text-gray-400 text-[10px] text-center px-8 font-bold leading-relaxed uppercase tracking-widest opacity-60">
                {selectedAsset === "SOL"
                    ? "Send SOL to this address on Solana Devnet."
                    : "Send USDC (SPL Token) to this address on Solana Devnet."}
            </p>
        </div>
    );
}
