"use client";

import { useWallet } from "@lazorkit/wallet";
import { Copy, QrCode } from "lucide-react";

/**
 * PATTERN: Smart Wallet Receive Flow
 * 
 * 📚 What You'll Learn:
 * • How to display the smart wallet address generated by Lazorkit.
 * • How to provide an easy receive experience with QR codes.
 */
export function ReceiveFund() {
    const { smartWalletPubkey } = useWallet();
    const address = smartWalletPubkey?.toBase58() || "";

    const copyAddress = () => {
        navigator.clipboard.writeText(address);
        alert("Address copied!");
    };

    return (
        <div className="flex flex-col items-center justify-center space-y-6 py-4">
            <div className="bg-white p-6 rounded-[32px] shadow-sm border border-gray-100 flex items-center justify-center">
                <img
                    src={`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${address}`}
                    alt="Wallet QR"
                    className="w-48 h-48 opacity-90"
                />
            </div>

            <div className="w-full bg-gray-50 border border-gray-100 rounded-2xl p-4 flex items-center justify-between">
                <div className="flex flex-col">
                    <span className="text-gray-400 text-[10px] font-bold uppercase tracking-widest leading-none mb-1">Your Smart Wallet</span>
                    <span className="text-gray-900 font-mono text-xs font-black truncate max-w-[200px]">
                        {address.slice(0, 8)}...{address.slice(-8)}
                    </span>
                </div>
                <button
                    onClick={copyAddress}
                    className="p-2.5 bg-white rounded-xl border border-gray-100 shadow-sm text-gray-500 hover:text-[#7857ff] transition-colors"
                >
                    <Copy size={16} />
                </button>
            </div>

            <p className="text-gray-400 text-[10px] text-center px-8 font-bold leading-relaxed uppercase tracking-widest opacity-60">
                Only send assets supported by the Solana Devnet to this address.
            </p>
        </div>
    );
}
